# Generated by Django 5.1.2 on 2024-10-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="status",
            field=models.CharField(
                choices=[("P", "Pending"), ("A", "Approved"), ("R", "Rejected")],
                default="P",
                max_length=1,
            ),
        ),
    ]
